### ISSUE TITLE
Publish on crates.io?

### ISSUE THREAD

**Issue by bnjbvr** [raftario/tracing-android#1]
Hi! Would be interested in using your crate, but I haven't found it on crates.io (the `tracing-android` on crates.io is a different one with fewer features). Would you be interested in publishing it on crates.io, please?

**Comment by raftario** [comment]
Yep, I actually tried to publish at some point but ran into the name conflict and didn't have any other name idea on the spot. I'd like to sort out #2 and update to tracing-subscriber 0.3 first if possible though. Also open to names 😄

**Comment by bnjbvr** [comment]
> Also open to names

Oh my :grinning: I would always go for a good pun, but nothing's obvious to me here. Will just let you with this grab bag of ideas: `tracedroid`, `androtracing`, `this-is-the-tracing-droid-youre-looking-for`, `tracing-logcat`, `paranoid-android` (see also: Radiohead), `traceoid`, `logoid`...

**Comment by raftario** [comment]
Ooooh paranoid-android is a really good one

**Comment by raftario** [comment]
[There it is !](https://docs.rs/paranoid-android)
